# Generated by Django 2.0.2 on 2018-03-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug2',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
