# Generated by Django 2.0.2 on 2018-03-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_slug2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug2',
        ),
    ]
