# Generated by Django 2.0.2 on 2018-03-04 20:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_category_slug2'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
