# Generated by Django 2.0.4 on 2018-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180421_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='Преподаватель'),
        ),
    ]
