# Generated by Django 2.0.4 on 2018-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180421_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagfiles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Категория'),
        ),
    ]
