# Generated by Django 2.0.4 on 2018-05-04 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 17, 50, 40, 600728, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=200),
        ),
    ]
