# Generated by Django 2.0.4 on 2018-05-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180514_2253'),
        ('main', '0014_auto_20180514_2301'),
    ]

    operations = [
    ]
