# Generated by Django 2.0.4 on 2018-05-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20180514_2303'),
        ('main', '0016_auto_20180514_2320'),
    ]

    operations = [
    ]
